# Generated by Django 5.0.6 on 2024-06-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mac_users',
            old_name='macaddr',
            new_name='macaddrs',
        ),
    ]
