# Generated by Django 5.0.3 on 2024-06-07 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mac_users_contel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddrs', models.CharField(max_length=20)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
